// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu4TTZ9T9W7oXQPh_LSF7_yehVeEw1J6k',
    appId: '1:330318806408:web:d62f078342eec2f0d9ce3d',
    messagingSenderId: '330318806408',
    projectId: 'fir-flutter-codelab-85165',
    authDomain: 'fir-flutter-codelab-85165.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-85165.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBaGH0Ct6MVqLelr3Gfj479CkuD4Ug_wc',
    appId: '1:330318806408:android:2def401fa40f88a6d9ce3d',
    messagingSenderId: '330318806408',
    projectId: 'fir-flutter-codelab-85165',
    storageBucket: 'fir-flutter-codelab-85165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_wI650_UIcpjnyDrATbMYkP5rZ8LuAw',
    appId: '1:330318806408:ios:8ace852f7b0688edd9ce3d',
    messagingSenderId: '330318806408',
    projectId: 'fir-flutter-codelab-85165',
    storageBucket: 'fir-flutter-codelab-85165.appspot.com',
    iosClientId: '330318806408-li7bjisk68bglco27gn0d8uh87jeht1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx_wI650_UIcpjnyDrATbMYkP5rZ8LuAw',
    appId: '1:330318806408:ios:8ace852f7b0688edd9ce3d',
    messagingSenderId: '330318806408',
    projectId: 'fir-flutter-codelab-85165',
    storageBucket: 'fir-flutter-codelab-85165.appspot.com',
    iosClientId: '330318806408-li7bjisk68bglco27gn0d8uh87jeht1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
